# Generated by Django 5.1.4 on 2025-01-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Use in Jupyter Notebooks'),
        ),
    ]
