# Generated by Django 5.1.4 on 2025-01-06 01:33

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_can_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
